token = '352896515:AAHoKqDa1ansmx_od3VMH-YXkdwPv8gQzY8'
# baseURL = 'https://chef-bot-server.herokuapp.com/api/'
# baseURL = 'http://batnet-host.ddns.net:5000/api/'
# baseImgURL = 'http://batnet-host.ddns.net:5000/'
baseURL = 'http://127.0.0.1:5000/api/'
baseImgURL = 'http://127.0.0.1:5000/'
# User state list
STATE_START = 'start'
STATE_IN_CART = 'in cart'
STATE_CHECKOUT = 'checkout'
STATE_OBTAIN_GPS_ADDRESS = 'gps address obtained'
STATE_VALID_ADDRESS = 'address valid'
STATE_INVALID_ADDRESS = 'address invalid'
STATE_OBTAIN_FULL_ADDRESS = 'full address optained'
STATE_CHECKOUT_COMPLETE = 'checkout completed'
